services:
  container:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        GROUP_NAME: ${GROUP_NAME}
        GROUP_ID: ${GROUP_ID}
    env_file:
      - .env
    ports:
    - "8888:8888"
    - "6006:6006"
    user: ${USER_NAME}:${GROUP_ID}
    entrypoint: ['/entrypoint.sh']
    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}